### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by xtuer** [Desdesdesgo/vue-scrollwatch#1]
The id should be **scrollDom** instead of **#scrollDom**:

if you want to define a container to scroll (not window)
如果你想指定滚动容器，而不是window

```
<div id="#scrollDom">
    ...
<div>
```

should changed to

```
<div id="scrollDom">
    ...
<div>
```

**Comment by Desdesdesgo** [comment]
It has been fixed. thank you.
