### ISSUE TITLE
使用radio的change事件时，会有一个问题

### ISSUE THREAD

**Issue by ikarosu** [Desdesdesgo/vue-scrollwatch#2]
```vue
<input
   type="radio"
   v-model="type"
   @change="scrollTo">
```

```javascript
scrollTo() {
   scrollWatch.scrollTo(this.type)
}
```
导致先选中再播放动画：
![20180808_105904](https://user-images.githubusercontent.com/10465428/43813944-82087c60-9afa-11e8-845f-eccd46190d2b.gif)
看了你的demo不会有这个问题，有啥解决办法吗

**Comment by Desdesdesgo** [comment]
点击以后发生了两件事：1.选中radio; 2.触发change事件开始执行动画。 
选中是立即发生的。动画是有一个执行时间的。
我的demo 代码中，是有回调函数spyDomChange 。 这个函数里面的代码实现了滚动之后改变样式。
你可以贴出更多的代码，我来帮你看看怎么优化

**Comment by ikarosu** [comment]
```html
<div class="type"
   v-for="(item, index) in types"
   :key="index"
   v-scrollWatch="{name:index,offset:0,callback:setActiveType}">
```
```javascript
setActiveType(node) {
  if (this.type !== node.name)
    this.type = node.name
}
```
也没啥特殊多的代码

**Comment by Desdesdesgo** [comment]
你可以用@click.prevent = "scrollTo" 阻止原生点击事件
最后在setActiveType  中 给这个raido 绑定的变量type赋值。
这样就能做到，动画切换好以后，radio 再选中 。

**Comment by ikarosu** [comment]
用click代替change并阻止原生事件，就没问题了
```vue
<label @click.prevent="scrollTo(index)">
  <span>text</span>
</label>
```
```javascript
scrollTo(index) {
   scrollWatch.scrollTo(index)
}
```
看来只能这样了
